# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: astroxyz

channels:
  - conda-forge

dependencies:
  - python=3.8

  - pip:
    - -r file:requirements.txt
